### ISSUE TITLE
2

### ISSUE THREAD

**Issue by W1ndys** [W1ndys/skills-hello-github-actions#13]
要实现这个功能，你需要编写一个Python脚本，该脚本在每次打开一个issue时触发并获取issue的内容。然后，你需要创建一个GitHub Actions工作流，该工作流将运行此脚本并使用`gh`命令行工具将结果评论到相应的issue下面。

以下是完成此任务所需的步骤：

1. **安装`gh`命令行工具**：确保你的GitHub Actions运行器上安装了`gh`命令行工具，因为我们需要它来与GitHub API进行交互。

2. **编写Python脚本**：创建一个Python脚本来获取新打开的issue的内容。

3. **编写GitHub Actions工作流**：创建一个工作流，当仓库中打开新的issue时触发，运行Python脚本，并使用`gh`命令行工具将结果评论到issue下面。

以下是具体的实现：

**Python脚本** (`get_issue_content.py`)：
```python
import os
import json
import requests

# GitHub Actions提供的issue信息环境变量
issue_number = os.environ.get('ISSUE_NUMBER')
repository = os.environ.get('GITHUB_REPOSITORY')

# GitHub API URL
api_url = f"https://api.github.com/repos/{repository}/issues/{issue_number}"

# 获取issue内容
response = requests.get(api_url)
issue_content = response.json()['body']

# 将issue内容保存到环境变量
print(f"::set-env name=ISSUE_CONTENT::{issue_content}")
```

**GitHub Actions工作流** (`.github/workflows/issue_comment.yml`)：
```yaml
name: Comment on New Issue

on: [issues]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip
        pip3 install requests

    - name: Run Python script to get issue content
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        python3 get_issue_content.py

    - name: Comment on issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 使用环境变量中的issue内容进行评论
        gh issue comment ${ISSUE_NUMBER} --body "${ISSUE_CONTENT}"
```

请注意，你需要在GitHub仓库的设置中生成一个`GITHUB_TOKEN`，并且将其作为secret添加到你的仓库中，以便工作流可以使用它来认证GitHub API。

此外，这个工作流仅在创建新issue时触发（`on: [issues]`），并且我们使用了`${{ github.event.issue.number }}`来获取当前issue的编号。

这个示例假设你已经有一个适当配置的Python环境，并且`gh`工具已经安装在运行工作流的机器上。如果`gh`工具没有预装，你需要在工作流中添加安装步骤。此外，由于GitHub Actions的运行环境可能没有预装Python，你可能需要添加步骤来安装Python和所需的依赖。
